const $AnyBlob = (tag, _1) => ({tag, _1});
const SvgString = x => x;
const JavascriptString = x => x;
const HtmlString = x => x;
const NodeImmutableBuffer = value0 => $AnyBlob("NodeImmutableBuffer", value0);
const WebBlob = value0 => $AnyBlob("WebBlob", value0);
const newtypeSvgString_ = {Coercible0: () => {}};
const newtypeJavascriptString_ = {Coercible0: () => {}};
const newtypeHtmlString_ = {Coercible0: () => {}};
export {$AnyBlob, HtmlString, JavascriptString, NodeImmutableBuffer, SvgString, WebBlob, newtypeHtmlString_, newtypeJavascriptString_, newtypeSvgString_};
